// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Euclideandist
float Euclideandist(float x1, float y1, float x2, float y2);
RcppExport SEXP _FredsVietorisRips_Euclideandist(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< float >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< float >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< float >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(Euclideandist(x1, y1, x2, y2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FredsVietorisRips_Euclideandist", (DL_FUNC) &_FredsVietorisRips_Euclideandist, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_FredsVietorisRips(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
